### ISSUE TITLE
npm install --save angular4-material-table

### ISSUE THREAD

**Issue by i-am-carol** [irossimoline/angular4-material-table#1]
I got the following error when I tried to install:

> npm ERR! code EINVALIDPACKAGENAME
> npm ERR! Invalid package name "@angular/cdk/collections": name can only contain URL-friendly characters

**Comment by irossimoline** [comment]
Hi @i-am-carol,

Which version of nodejs/npm have you installed? Have you tried to update them? I was able to install this package without any issue.

**Comment by irossimoline** [comment]
@i-am-carol, I proceed to close this issue, as we had no additional feedback.
