### ISSUE TITLE
how to use dropdown list

### ISSUE THREAD

**Issue by BahgatMashaly** [irossimoline/angular4-material-table#11]
Hello Dear,

Could you give use a simple example how to use dropdown list

**Comment by irossimoline** [comment]
Hi there,

To use a dropdown is pretty simple. You can have a component property to store the list displayed by the dropdown, and then access it from the `html` template as a usual dropdown list.

**Comment by irossimoline** [comment]
Hi @BahgatMashaly, due to inactivity I'll close this issue.
If you have any other question please open a new one.
