### ISSUE TITLE
Can't bind to 'formControl' since it isn't a known property of 'input'.

### ISSUE THREAD

**Issue by pdvbalaji** [irossimoline/angular4-material-table#12]
Hello sir,

 I try to implement your code in my project but getting errors like this , Can you please help to solve this problem . Thank you

Can't bind to 'formControl' since it isn't a known property of 'input'. ("
        <mat-cell *matCellDef="let row">
            <mat-form-field >
                <input [ERROR ->][formControl]="row.validator.controls['name']" [readonly]="!row.editing" placeholder="Name" [(ngModel"): ng:///AppModule/FormGenerationComponent.html@5:23
Can't bind to 'ngModel' since it isn't a known property of 'input'. (" <input [formControl]="row.validator.controls['name']" [readonly]="!row.editing" placeholder="Name" [ERROR ->][(ngModel)]="row.currentData.name" matInput>
            </mat-form-field>
        </mat-cell>
"): ng:///AppModule/FormGenerationComponent.html@5:115
Can't bind to 'formControl' since it isn't a known property of 'input'. ("   <mat-form-field floatPlaceholder="{{ row.editing ? 'float' : 'never'}}">
                <input [ERROR ->][formControl]="row.validator.controls['age']" type="number" placeholder="Age" [(ngModel)]="row.curren"): ng:///AppModule/FormGenerationComponent.html@13:23
Can't bind to 'ngModel' since it isn't a known property of 'input'. ("               <input [formControl]="row.validator.controls['age']" type="number" placeholder="Age" [ERROR ->][(ngModel)]="row.currentData.age" matInput>
            </mat-form-field>
        </mat-cell>
"): ng:///AppModule/FormGenerationComponent.html@13:101
No provider for NgControl ("
        <mat-cell *matCellDef="let row">
            <mat-form-field >
                [ERROR ->]<input [formControl]="row.validator.controls['name']" [readonly]="!row.editing" placeholder="Name" [("): ng:///AppModule/FormGenerationComponent.html@5:16
No provider for NgControl ("          <mat-form-field floatPlaceholder="{{ row.editing ? 'float' : 'never'}}">
                [ERROR ->]<input [formControl]="row.validator.controls['age']" type="number" placeholder="Age" [(ngModel)]="row"): ng:///AppModule/FormGenerationComponent.html@13:16

**Comment by irossimoline** [comment]
Hi @pdvbalaji, did you forget to import `FormsModule`/`ReactiveFormsModule` in your own module?

**Comment by pdvbalaji** [comment]
I added Forms Module ,But i did not  add ReactiveFormsModule  ,shall i add it

**Comment by pdvbalaji** [comment]
plz help to solve this , I am using typescript with dotnet

**Comment by irossimoline** [comment]
@pdvbalaji, if you are using `formControl` inside an `input` you should import `ReactiveFormsModule`.

[This SO question](https://stackoverflow.com/questions/43220348/cant-bind-to-formcontrol-since-it-isnt-a-known-property-of-input-angular) talks about the same problem that you are experiencing.

**Comment by irossimoline** [comment]
@pdvbalaji, could you solve the issue?

**Comment by irossimoline** [comment]
@pdvbalaji

As no answer received I'll assume you could solve it and I'll close this issue. If you keep having issues to make it work you can open a new issue.
