### ISSUE TITLE
Adding documentation or the source code demonstrating the approach. 

### ISSUE THREAD

**Issue by kal93** [irossimoline/angular4-material-table#16]
Is the source code for this package public?

There're very few examples of extending cdk table.So far I'm aware of only two such packages viz this one and the other is [terminus ui](https://github.com/GetTerminus/terminus-ui) so I think it would be great if this repo provides some sort of technical details or code as to how you guys approached it.

**Comment by irossimoline** [comment]
Hi @kal93,

The source code of this package is public. You can check the implementation under `src` folder. The code is documented, and I think it is also self explanatory.

If you have any specific doubt please let me know.

**Comment by kal93** [comment]
I did have a look at the code and it seems that this package extends the cdk DataSource which is then used with `mat-table`.I was under the impression that this package had built a whole new table with its own templates on top of cdk table which looked exactly like `mat-table`.

Thanks @irossimoline .

**Comment by irossimoline** [comment]
Cool you had a look on it @kal93. You are right: the idea behind this package is just to extend Angular's framework to allow CRUD and data validation easily, but avoiding reinventing the wheel. 😃 

If you have any other doubt please feel free to open a new issue.
