### ISSUE TITLE
Release for Angular 7

### ISSUE THREAD

**Issue by lakinduakash** [irossimoline/angular4-material-table#30]
Any idea for release for angular 7 may valuable

**Comment by irossimoline** [comment]
Published a new version for Angular 7.

It mainly update library dependencies, and also implements a refactor to separate template-driven from reactive-forms technique.
It does support both approaches, but separates internal behavior manipulating the data directly on FormGroup and FormControls if using reactive-forms approach.
In case of using template-driven, the data correctness validation before submitting (edit & create confirmation) must be done on client side (user's code).
