### ISSUE TITLE
error TS2416: Property 'connect' in type 'TableDataSource<T>' is not assignable to the same property in base type 'DataSource<TableElement<T>>'.

### ISSUE THREAD

**Issue by rsteaburdea** [irossimoline/angular4-material-table#37]
Hello

I get this error when I try to implement locally your [example](https://stackblitz.com/edit/angular-tj9f6y?file=src%2Fapp%2Fapp.module.ts) and I suppose it's because **Angular 8** is not backward compatible with **Angular 4**.

![Error Image](https://user-images.githubusercontent.com/40496269/62524682-b8d59900-b83e-11e9-8585-8491e3be7873.png)

What is this error about?
Can you help me fix it?

**Additional details:**

- Angular 8
- @angular/cdk@8.1.2
- hammerjs@2.0.8
- @angular/flex-layout@8.0.0-beta.26
- angular4-material-table@0.8.0
- @angular/material@8.1.2
-  rxjs@6.4.0
```
npm install --save @angular/material @angular/cdk
npm install --save @angular/flex-layout
npm install --save hammerjs
npm install --save angular4-material-table
npm install --save rxjs
```

**Comment by AlexMihov96** [comment]
I do experience same issue running the package after updating to Angular 8, is it a know issue and can we workaround it somehow untill it's fixed?

**Comment by vandervyvere** [comment]
For me how I resolved it was by deleting the node_modules folder located in the angular4-material-table folder. After this when I build/serve i do not get the error anymore.

**Comment by rsteaburdea** [comment]
It doesn't work for me!

![image](https://user-images.githubusercontent.com/40496269/66639378-668a6d00-ec1f-11e9-9ab4-c06317bdd615.png)

**Comment by Ricardo110** [comment]
Hi, I' getting the same error. Did you find a way to fix this issue?

**Comment by vandervyvere** [comment]
Did you try my solution mentioned above, not sure if it worked for everyone.

"For me how I resolved it was by deleting the node_modules folder located in the angular4-material-table folder. After this when I build/serve i do not get the error anymore."

**Comment by Ricardo110** [comment]
Yes I tried that, still getting the same error when I tried to run it. I also tried deleting all of the node-mudules folder as well and still gives me the error

![image](https://user-images.githubusercontent.com/5233649/76734475-a8d64e00-676b-11ea-9c62-354c9707895d.png)

**Comment by AlexMihov96** [comment]
I solved that error by deleting node_modules in angular4-material-table folder then installing it again via npm install, then I ran my project and it started successfully.

**Comment by dilipsarkar** [comment]
I was also getting the same error but in my case it was due to the mismatch of data type between the `DataSource` class and `connect` method `Observable` return type

```
export class ActionItemDataSource implements DataSource<Task> {
  
  connect(collectionViewer: CollectionViewer): Observable<Task[]> {
      return this.taskSubject.asObservable();
  }

}
```

Please pay attention to the `DataSource` type i.e. `Task` and the `connect` method `Observable` type `Task[]` i.e. it should be an array of the `DataSource` element type.

**Comment by asukkoor** [comment]
Has anyone identified a solution for this issue? Deleting the node_modules folder doesn't fix the issue.

**Comment by asukkoor** [comment]
> Hello
> 
> I get this error when I try to implement locally your [example](https://stackblitz.com/edit/angular-tj9f6y?file=src%2Fapp%2Fapp.module.ts) and I suppose it's because **Angular 8** is not backward compatible with **Angular 4**.
> 
> ![Error Image](https://user-images.githubusercontent.com/40496269/62524682-b8d59900-b83e-11e9-8585-8491e3be7873.png)
> 
> What is this error about?
> Can you help me fix it?
> 
> **Additional details:**
> 
> * Angular 8
> * @angular/cdk@8.1.2
> * hammerjs@2.0.8
> * @angular/flex-layout@8.0.0-beta.26
> * angular4-material-table@0.8.0
> * @angular/material@8.1.2
> * rxjs@6.4.0
> 
> ```
> npm install --save @angular/material @angular/cdk
> npm install --save @angular/flex-layout
> npm install --save hammerjs
> npm install --save angular4-material-table
> npm install --save rxjs
> ```

Did you resolve this issue?

**Comment by asukkoor** [comment]
Actually, deleting node_modules in angular4-material-table folder works!

**Comment by rsteaburdea** [comment]
@AlexMihov96 @vandervyvere @asukkoor can you provide me an example of this issue working? 

For example a github repository with this table? 
Also some photos attached with steps to fix it would be usefull.

For me it's still not working.

**Comment by AlexMihov96** [comment]
I no longer have access to this repo, but you should just delete node_modules in angular4-material-table folder ( which is in node_modules in your current project ). then installing it again via npm install, it used to work for me 100% of the times @rsteaburdea

**Comment by rsteaburdea** [comment]
@AlexMihov96 I don't have very much experience with Angular. I read documentation of this table and is not very clear to me. I tried to copy-paste this [example](https://stackblitz.com/edit/angular-tj9f6y?file=src%2Fapp%2Fapp.module.ts) on my local computer after your workaround it didn't work. 

Can you help me please?

**Comment by AlexMihov96** [comment]
@rsteaburdea Do you have Angular 7 globally installed or it is Angular 8/9, in this example you can see in package.json that angular is at version 7, you need to match the same version in order to run. Do not take the example, install the package in your project (create empty one) and follow the instructions. Note that this package does not support Angular 9

**Comment by rsteaburdea** [comment]
@AlexMihov96 I checked now and it looks like I have Angular 9. I checked on [npm](https://www.npmjs.com/package/angular4-material-table) and they offer support even for Angular 8. From my knowledge Angular 9 is backward compatible with Angular 8. 

Also from what I remember they have logic over **DataSource** from **angular/cdk/collections** and from documentation is not very clear to me how to use this project.

**Comment by AlexMihov96** [comment]
@rsteaburdea As I remember, I lastly run this package on Angular 8 and I did [this](https://github.com/irossimoline/angular4-material-table/issues/37#issuecomment-599425658)
Haven't even tried Angular 9, please try to downgrade 9 to 8 globally and try it again, otherwise dont use this package because it will not support newest Angular features, Angular 9, 10 and etc..

**Comment by AlexMihov96** [comment]
@rsteaburdea Its pretty simple to make a wrap over original [Material table ](https://material.angular.io/components/table/overview), if you need anything more.
I wish you luck :))
