### ISSUE TITLE
could you use typescript method to colon object instead of lodash.com cloneDeep

### ISSUE THREAD

**Issue by BahgatMashaly** [irossimoline/angular4-material-table#9]
could you use typescript method to colon object instead of lodash.com cloneDeep

like this

let swallowClone = { ...original };

or

let swallowClone= Object.assign({}, original);

**Comment by irossimoline** [comment]
Hi there,

It can be done a shallowClone, but you will never be sure if a mutability can affect your cloned data.
Could you explain why would you require it?

Thank you.

**Comment by irossimoline** [comment]
Hi @BahgatMashaly, due to inactivity I'll close this issue.
If you have any other question please open a new one.
